-- impute NULL values with zero
-- overwrite "features"

SELECT
  customer_id,
  brand,
  promo_sensitive,
  brand_seasonality,
  IFNULL( total_sale_quantity_1m, 0) AS total_sale_quantity_1m ,
  IFNULL( max_sale_amount_1m, 0 ) AS max_sale_amount_1m ,
  IFNULL( max_sale_quantity_1m, 0 ) AS max_sale_quantity_1m ,
  IFNULL( total_returned_items_1m, 0 ) AS total_returned_items_1m ,
  IFNULL( distinct_products_1m, 0 ) AS distinct_products_1m ,
  IFNULL( distinct_chains_1m, 0 ) AS distinct_chains_1m ,
  IFNULL( distinct_category_1m, 0 ) AS distinct_category_1m ,
  IFNULL( distinct_days_shopped_1m, 0 ) AS distinct_days_shopped_1m ,
  IFNULL( aov_1m, 0 ) AS aov_1m,
  IFNULL( total_sale_quantity_3m, 0 ) AS total_sale_quantity_3m ,
  IFNULL( max_sale_amount_3m, 0 ) AS max_sale_amount_3m ,
  IFNULL( max_sale_quantity_3m, 0 ) AS max_sale_quantity_3m ,
  IFNULL( total_returned_items_3m, 0 ) AS total_returned_items_3m ,
  IFNULL( distinct_products_3m, 0 ) AS distinct_products_3m ,
  IFNULL( distinct_chains_3m, 0 ) AS distinct_chains_3m ,
  IFNULL( distinct_category_3m, 0 ) AS distinct_category_3m ,
  IFNULL( distinct_days_shopped_3m, 0 ) AS distinct_days_shopped_3m ,
  IFNULL( aov_3m, 0 ) AS aov_3m,
  IFNULL( total_sale_quantity_6m, 0 ) AS total_sale_quantity_6m ,
  IFNULL( max_sale_amount_6m, 0 ) AS max_sale_amount_6m ,
  IFNULL( max_sale_quantity_6m, 0 ) AS max_sale_quantity_6m ,
  IFNULL( total_returned_items_6m, 0 ) AS total_returned_items_6m ,
  IFNULL( distinct_products_6m, 0 ) AS distinct_products_6m ,
  IFNULL( distinct_chains_6m, 0 ) AS distinct_chains_6m ,
  IFNULL( distinct_category_6m, 0 ) AS distinct_category_6m ,
  IFNULL( distinct_days_shopped_6m, 0 ) AS distinct_days_shopped_6m ,
  IFNULL( aov_6m, 0 ) AS aov_6m,
  IFNULL( total_sale_quantity_12m, 0 ) AS total_sale_quantity_12m ,
  IFNULL( max_sale_amount_12m, 0 ) AS max_sale_amount_12m ,
  IFNULL( max_sale_quantity_12m, 0 ) AS max_sale_quantity_12m ,
  IFNULL( total_returned_items_12m, 0 ) AS total_returned_items_12m ,
  IFNULL( distinct_products_12m, 0 ) AS distinct_products_12m ,
  IFNULL( distinct_chains_12m, 0 ) AS distinct_chains_12m ,
  IFNULL( distinct_category_12m, 0 ) AS distinct_category_12m ,
  IFNULL( distinct_days_shopped_12m, 0 ) AS distinct_days_shopped_12m ,
  IFNULL( aov_12m, 0 ) AS aov_12m,
  IFNULL( overall_sale_quantity_1m, 0 ) AS overall_sale_quantity_1m ,
  IFNULL( overall_returned_items_1m, 0 ) AS overall_returned_items_1m ,
  IFNULL( overall_distinct_products_1m, 0 ) AS overall_distinct_products_1m ,
  IFNULL( overall_distinct_brands_1m, 0 ) AS overall_distinct_brands_1m ,
  IFNULL( overall_distinct_chains_1m, 0 ) AS overall_distinct_chains_1m ,
  IFNULL( overall_distinct_category_1m, 0 ) AS overall_distinct_category_1m ,
  IFNULL( overall_distinct_days_shopped_1m, 0 ) AS overall_distinct_days_shopped_1m ,
  IFNULL( overall_aov_1m, 0 ) AS overall_aov_1m ,
  IFNULL( overall_sale_quantity_3m, 0 ) AS overall_sale_quantity_3m ,
  IFNULL( overall_returned_items_3m, 0 ) AS overall_returned_items_3m ,
  IFNULL( overall_distinct_products_3m, 0 ) AS overall_distinct_products_3m ,
  IFNULL( overall_distinct_brands_3m, 0 ) AS overall_distinct_brands_3m ,
  IFNULL( overall_distinct_chains_3m, 0 ) AS overall_distinct_chains_3m ,
  IFNULL( overall_distinct_category_3m, 0 ) AS overall_distinct_category_3m ,
  IFNULL( overall_distinct_days_shopped_3m, 0 ) AS overall_distinct_days_shopped_3m ,
  IFNULL( overall_aov_3m, 0 ) AS overall_aov_3m ,
  IFNULL( overall_sale_quantity_6m, 0 ) AS overall_sale_quantity_6m ,
  IFNULL( overall_returned_items_6m, 0 ) AS overall_returned_items_6m ,
  IFNULL( overall_distinct_products_6m, 0 ) AS overall_distinct_products_6m ,
  IFNULL( overall_distinct_brands_6m, 0 ) AS overall_distinct_brands_6m ,
  IFNULL( overall_distinct_chains_6m, 0 ) AS overall_distinct_chains_6m ,
  IFNULL( overall_distinct_category_6m, 0 ) AS overall_distinct_category_6m ,
  IFNULL( overall_distinct_days_shopped_6m, 0 ) AS overall_distinct_days_shopped_6m ,
  IFNULL( overall_aov_6m, 0 ) AS overall_aov_6m ,
  IFNULL( overall_sale_quantity_12m, 0 ) AS overall_sale_quantity_12m ,
  IFNULL( overall_returned_items_12m, 0 ) AS overall_returned_items_12m ,
  IFNULL( overall_distinct_products_12m, 0 ) AS overall_distinct_products_12m ,
  IFNULL( overall_distinct_brands_12m, 0 ) AS overall_distinct_brands_12m ,
  IFNULL( overall_distinct_chains_12m, 0 ) AS overall_distinct_chains_12m ,
  IFNULL( overall_distinct_category_12m, 0 ) AS overall_distinct_category_12m ,
  IFNULL( overall_distinct_days_shopped_12m, 0 ) AS overall_distinct_days_shopped_12m ,
  IFNULL( overall_aov_12m, 0 ) AS overall_aov_12m ,
  label
FROM
`PROJECT.DATASET.features`