-- type cast
-- overwrite "features"

SELECT
	CAST(customer_id AS STRING) AS customer_id,
	CAST( brand AS STRING ) AS brand,
	CAST( promo_sensitive AS INT64 ) AS promo_sensitive,
	CAST( brand_seasonality AS INT64 ) AS brand_seasonality,
	CAST( total_sale_quantity_1m AS INT64 ) AS total_sale_quantity_1m ,
	CAST( max_sale_amount_1m AS INT64 ) AS max_sale_amount_1m ,
	CAST( max_sale_quantity_1m AS INT64 ) AS max_sale_quantity_1m ,
	CAST( total_returned_items_1m AS INT64 ) AS total_returned_items_1m ,
	CAST( distinct_products_1m AS INT64 ) AS distinct_products_1m ,
	CAST( distinct_chains_1m AS INT64 ) AS distinct_chains_1m ,
	CAST( distinct_category_1m AS INT64 ) AS distinct_category_1m ,
	CAST( distinct_days_shopped_1m AS INT64 ) AS distinct_days_shopped_1m ,
	CAST( aov_1m AS INT64 ) AS aov_1m,
	CAST( total_sale_quantity_3m AS INT64 ) AS total_sale_quantity_3m ,
	CAST( max_sale_amount_3m AS INT64 ) AS max_sale_amount_3m ,
	CAST( max_sale_quantity_3m AS INT64 ) AS max_sale_quantity_3m ,
	CAST( total_returned_items_3m AS INT64 ) AS total_returned_items_3m ,
	CAST( distinct_products_3m AS INT64 ) AS distinct_products_3m ,
	CAST( distinct_chains_3m AS INT64 ) AS distinct_chains_3m ,
	CAST( distinct_category_3m AS INT64 ) AS distinct_category_3m ,
	CAST( distinct_days_shopped_3m AS INT64 ) AS distinct_days_shopped_3m ,
	CAST( aov_3m AS INT64 ) AS aov_3m,
	CAST( total_sale_quantity_6m AS INT64 ) AS total_sale_quantity_6m ,
	CAST( max_sale_amount_6m AS INT64 ) AS max_sale_amount_6m ,
	CAST( max_sale_quantity_6m AS INT64 ) AS max_sale_quantity_6m ,
	CAST( total_returned_items_6m AS INT64 ) AS total_returned_items_6m ,
	CAST( distinct_products_6m AS INT64 ) AS distinct_products_6m ,
	CAST( distinct_chains_6m AS INT64 ) AS distinct_chains_6m ,
	CAST( distinct_category_6m AS INT64 ) AS distinct_category_6m ,
	CAST( distinct_days_shopped_6m AS INT64 ) AS distinct_days_shopped_6m ,
	CAST( aov_6m AS INT64 ) AS aov_6m,
	CAST( total_sale_quantity_12m AS INT64 ) AS total_sale_quantity_12m ,
	CAST( max_sale_amount_12m AS INT64 ) AS max_sale_amount_12m ,
	CAST( max_sale_quantity_12m AS INT64 ) AS max_sale_quantity_12m ,
	CAST( total_returned_items_12m AS INT64 ) AS total_returned_items_12m ,
	CAST( distinct_products_12m AS INT64 ) AS distinct_products_12m ,
	CAST( distinct_chains_12m AS INT64 ) AS distinct_chains_12m ,
	CAST( distinct_category_12m AS INT64 ) AS distinct_category_12m ,
	CAST( distinct_days_shopped_12m AS INT64 ) AS distinct_days_shopped_12m ,
	CAST( aov_12m AS INT64 ) AS aov_12m,
	CAST( overall_sale_quantity_1m AS INT64 ) AS overall_sale_quantity_1m ,
	CAST( overall_returned_items_1m AS INT64 ) AS overall_returned_items_1m ,
	CAST( overall_distinct_products_1m AS INT64 ) AS overall_distinct_products_1m ,
	CAST( overall_distinct_brands_1m AS INT64 ) AS overall_distinct_brands_1m ,
	CAST( overall_distinct_chains_1m AS INT64 ) AS overall_distinct_chains_1m ,
	CAST( overall_distinct_category_1m AS INT64 ) AS overall_distinct_category_1m ,
	CAST( overall_distinct_days_shopped_1m AS INT64 ) AS overall_distinct_days_shopped_1m ,
	CAST( overall_aov_1m AS INT64 ) AS overall_aov_1m ,
	CAST( overall_sale_quantity_3m AS INT64 ) AS overall_sale_quantity_3m ,
	CAST( overall_returned_items_3m AS INT64 ) AS overall_returned_items_3m ,
	CAST( overall_distinct_products_3m AS INT64 ) AS overall_distinct_products_3m ,
	CAST( overall_distinct_brands_3m AS INT64 ) AS overall_distinct_brands_3m ,
	CAST( overall_distinct_chains_3m AS INT64 ) AS overall_distinct_chains_3m ,
	CAST( overall_distinct_category_3m AS INT64 ) AS overall_distinct_category_3m ,
	CAST( overall_distinct_days_shopped_3m AS INT64 ) AS overall_distinct_days_shopped_3m ,
	CAST( overall_aov_3m AS INT64 ) AS overall_aov_3m ,
	CAST( overall_sale_quantity_6m AS INT64 ) AS overall_sale_quantity_6m ,
	CAST( overall_returned_items_6m AS INT64 ) AS overall_returned_items_6m ,
	CAST( overall_distinct_products_6m AS INT64 ) AS overall_distinct_products_6m ,
	CAST( overall_distinct_brands_6m AS INT64 ) AS overall_distinct_brands_6m ,
	CAST( overall_distinct_chains_6m AS INT64 ) AS overall_distinct_chains_6m ,
	CAST( overall_distinct_category_6m AS INT64 ) AS overall_distinct_category_6m ,
	CAST( overall_distinct_days_shopped_6m AS INT64 ) AS overall_distinct_days_shopped_6m ,
	CAST( overall_aov_6m AS INT64 ) AS overall_aov_6m ,
	CAST( overall_sale_quantity_12m AS INT64 ) AS overall_sale_quantity_12m ,
	CAST( overall_returned_items_12m AS INT64 ) AS overall_returned_items_12m ,
	CAST( overall_distinct_products_12m AS INT64 ) AS overall_distinct_products_12m ,
	CAST( overall_distinct_brands_12m AS INT64 ) AS overall_distinct_brands_12m ,
	CAST( overall_distinct_chains_12m AS INT64 ) AS overall_distinct_chains_12m ,
	CAST( overall_distinct_category_12m AS INT64 ) AS overall_distinct_category_12m ,
	CAST( overall_distinct_days_shopped_12m AS INT64 ) AS overall_distinct_days_shopped_12m ,
	CAST( overall_aov_12m AS INT64 ) AS overall_aov_12m ,
	CAST(label AS INT64) AS label
FROM
`PROJECT.DATASET.features`